MVCBlog/Models/ORM/Entity/BlogPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCBlog.Models.ORM.Entity
{
    public class BlogPost : BaseEntity
    {

        public string Title { get; set; }

        public string Content { get; set; }

        public int CategoryID { get; set; }

        public string ImagePath { get; set; }

        [ForeignKey("CategoryID")]
        public virtual Category Category { get; set; }

        public virtual List<BlogPostComment> BlogPostComments{ get; set; }
    }
}

MVCBlog/Areas/Admin/Controllers/BlogPostController.cs
using MVCBlog.Areas.Admin.Models.DTO;
using MVCBlog.Areas.Admin.Models.Services.HTMLDataSourceServices;
using MVCBlog.Models.ORM.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBlog.Areas.Admin.Controllers
{
    public class BlogPostController : BaseController
    {
        public ActionResult Index()
        {
            List<BlogPostVM> model = db.BlogPosts.Where(x => x.IsDeleted == false).OrderBy(x => x.AddDate).Select(x => new BlogPostVM()
            {
                Title = x.Title,
                CategoryName = x.Category.Name,
                ID = x.ID
            }).ToList();

            return View(model);
        }

        public ActionResult AddBlogPost()
        {
            BlogPostVM model = new BlogPostVM();
            model.drpCategories = DrpServices.getDrpCategories();


            return View(model);
        }


        [ValidateInput(false)]
        [HttpPost]
        public ActionResult AddBlogPost(BlogPostVM model)
        {
            BlogPostVM vmodel = new BlogPostVM();
            vmodel.drpCategories = DrpServices.getDrpCategories();

            if (ModelState.IsValid)
            {
                string filename = "";
                foreach (string name in Request.Files)
                {
                   
                    model.PostImage = Request.Files[name];
                    string ext = Path.GetExtension(Request.Files[name].FileName);
                    if (ext == ".jpg" || ext == ".jpeg" || ext == ".png")
                    {
                        string uniqnumber = Guid.NewGuid().ToString();
                        filename = uniqnumber + model.PostImage.FileName;
                        model.PostImage.SaveAs(Server.MapPath("~/Areas/Admin/Content/Site/images/blogpost/" + filename));
                    }

                }

                BlogPost blogpost = new BlogPost();
                blogpost.CategoryID = model.CategoryID;
                blogpost.Title = model.Title;
                blogpost.Content = model.Content;
                blogpost.ImagePath = filename;

                db.BlogPosts.Add(blogpost);
                //db.SaveChanges();
                ViewBag.IslemDurum = 1;
                return View(vmodel);
            }
            else
            {
                ViewBag.IslemDurum = 2;
                return View(vmodel);
            }

        }

        public ActionResult UpdateBlogPost(int id)
        {
            BlogPost blogpost = db.BlogPosts.FirstOrDefault(x => x.ID == id);
            BlogPostVM model = new BlogPostVM();
            model.CategoryID = blogpost.CategoryID;
            model.Title = blogpost.Title;
            model.Content = blogpost.Content;
            model.drpCategories = DrpServices.getDrpCategories();

            return View(model);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult UpdateBlogPost(BlogPostVM model)
        {
            model.drpCategories = DrpServices.getDrpCategories();
            if (ModelState.IsValid)
            {
                BlogPost blogpost = db.BlogPosts.FirstOrDefault(x => x.ID == model.ID);
                blogpost.CategoryID = model.CategoryID;
                blogpost.Title = model.Title;
                blogpost.Content = model.Content;

                db.SaveChanges();
                ViewBag.IslemDurum = 1;

                return View(model);
            }
            else
            {
                ViewBag.IslemDurum = 2;
                return View(model);
            }

        }

        public JsonResult DeleteBlogPost(int id)
        {
            BlogPost blogpost = db.BlogPosts.FirstOrDefault(x => x.ID == id);
            blogpost.IsDeleted = true;
            blogpost.DeleteDate = DateTime.Now;
            db.SaveChanges();

            return Json("");
        }
    }
}

MVCBlog/Areas/Admin/Views/BlogPost/AddBlogPost.cshtml
@{
    ViewBag.Title = "AddBlogPost";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
<section class="content-header">
    <h1>
        Blog Yazısı Ekleme İşlemi
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Form</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("/Areas/Admin/Views/Shared/Partial/FormMessagesPart.cshtml")
            <script src="~/Scripts/ckeditor/ckeditor.js"></script>
            <div class="box box-primary">

                <!-- form start -->
                @using (Html.BeginForm("AddBlogPost", "BlogPost", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/BlogPostForm")
                }
            </div>
        </div>
    </div>
</section>

MVCBlog/Areas/Admin/Views/BlogPost/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
@model List<MVCBlog.Areas.Admin.Models.DTO.BlogPostVM>
<link href="~/Areas/Admin/Content/css/dataTables.bootstrap.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap.min.js"></script>
<script src="~/Scripts/custom/deleteRecordTable.js"></script>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Haber Listesi
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Data Table With Full Features</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Kategori</th>
                                <th>Başlık</th>
                                <th>İşlem</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr id="a_@item.ID">

                                    <td>@item.ID</td>
                                    <td>@item.CategoryName</td>
                                    <td>@item.Title</td>
                                    <td><a href="/Admin/BlogPost/UpdateBlogPost/@item.ID">Güncelle</a></td>
                                    <td><img src="~/Areas/Admin/Content/img/delete-icon.png" width="30" height="30" style="cursor:pointer" onclick="Delete('/Admin/BlogPost/DeleteBlogPost/',@item.ID)" /></td>
                                </tr>
                            }

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Kategori</th>
                                <th>Başlık</th>
                                <th>İşlem</th>
                                <th>İşlem</th>
                            </tr>
                        </tfoot>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->

<script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
</script>

MVCBlog/Areas/Admin/Views/BlogPost/UpdateBlogPost.cshtml
@{
    ViewBag.Title = "UpdateBlogPost";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
<section class="content-header">
    <h1>
        Blog Yazısı Güncelleme İşlemi
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Forms</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>

<section class="content">

    <div class="row">

        <div class="col-md-9">

            @Html.Partial("/Areas/Admin/Views/Shared/Partial/FormMessagesPart.cshtml")

            <script src="~/Scripts/ckeditor/ckeditor.js"></script>
            <div class="box box-primary">

                <!-- form start -->
                @using (Html.BeginForm("UpdateBlogPost", "BlogPost", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/BlogPostForm")
                }
            </div>
        </div>
    </div>
</section>